=== emtiu/piratenmandate/piratenmandate.dtd
<!ELEMENT piratenmandate (bundesland+) >

<!ELEMENT bundesland (parlament?, gebiet*) >
<!ATTLIST bundesland name CDATA #REQUIRED >
<!ATTLIST bundesland gs CDATA #REQUIRED >
<!ATTLIST bundesland localpirates CDATA #IMPLIED >

<!ELEMENT gebiet (parlament*, gebiet*) >
<!ATTLIST gebiet type CDATA #REQUIRED >
<!ATTLIST gebiet name CDATA #REQUIRED >
<!ATTLIST gebiet gs CDATA #IMPLIED >
<!ATTLIST gebiet localkey CDATA #IMPLIED > <!--Amtlicher Schlüssel, falls kein gs-->
<!ATTLIST gebiet arbkey CDATA #IMPLIED > <!--Beliebiger Schlüssel, falls sonst keiner-->
<!ATTLIST gebiet localpirates CDATA #IMPLIED >

<!ELEMENT parlament (mandat+, fraktion?, story?) >
<!ATTLIST parlament name CDATA #REQUIRED >
<!ATTLIST parlament seats CDATA #IMPLIED >
<!ATTLIST parlament ris CDATA #IMPLIED >

<!ELEMENT mandat (#PCDATA) >
<!ATTLIST mandat multi CDATA #IMPLIED >
<!ATTLIST mandat type (pirat | transfer) #REQUIRED >
<!ATTLIST mandat from CDATA #IMPLIED >

<!ELEMENT fraktion (partner*) >
<!ATTLIST fraktion type (piraten | gemeinsam | fremd | none | unknown) #REQUIRED >
<!ATTLIST fraktion name CDATA #IMPLIED >
<!ATTLIST fraktion url CDATA #IMPLIED >
<!ATTLIST fraktion feed CDATA #IMPLIED >

<!ELEMENT story (#PCDATA) >
<!ATTLIST story source CDATA #IMPLIED >

<!ELEMENT partner EMPTY >
<!ATTLIST partner partei CDATA #REQUIRED >
<!ATTLIST partner num CDATA #IMPLIED >

=== emtiu/piratenmandate/piratenmandate.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE piratenmandate SYSTEM "piratenmandate.dtd">

<piratenmandate>
  <bundesland name="Schleswig-Holstein" gs="01000000" localpirates="http://landesportal.piratenpartei-sh.de/">
    <gebiet type="Kreisfreie Stadt" name="Kiel" gs="01002000" localpirates="http://landesportal.piratenpartei-sh.de/kiel/">
      <parlament name="Ratsversammlung" seats="53" ris="http://ratsinfo.kiel.de/bi/pa021.asp">
        <mandat type="pirat">Sven Seele</mandat>
        <mandat type="pirat">Marcel Schmidt</mandat>
        <fraktion type="piraten" url="http://landesportal.piratenpartei-sh.de/fraktion-kiel/" />
      </parlament>
    </gebiet>
    <gebiet type="Kreisfreie Stadt" name="Lübeck" gs="01003000" localpirates="http://landesportal.piratenpartei-sh.de/luebeck/">
      <parlament name="Bürgerschaft" seats="49" ris="http://luebeck.de/stadt_politik/buergerinfo/bi/pa021.asp">
        <mandat type="pirat">Oliver Dedow</mandat>
        <fraktion type="gemeinsam" name="Die Partei-Piraten">
          <partner partei="Die PARTEI" num="1"/>
        </fraktion>
      </parlament>
    </gebiet>
    <gebiet type="Kreisfreie Stadt" name="Neumünster" gs="01004000" localpirates="http://landesportal.piratenpartei-sh.de/nms/">
      <parlament name="Ratsversammlung" seats="42" ris="https://w3.neumuenster.de/session/bi/kp0040.php?__kgrnr=1&amp;">
        <mandat type="pirat">Thomas Puls</mandat>
        <fraktion type="gemeinsam" name="BfB/PIRATEN">
          <partner partei="Wählergemeinschaft" num="3"/>
        </fraktion>
      </parlament>
    </gebiet>
    <gebiet type="Landkreis" name="Kreis Steinburg" gs="01061000" localpirates="http://landesportal.piratenpartei-sh.de/steinburg/">
      <parlament name="Kreistag" seats="44" ris="https://www.steinburg.de/144_150.htm">
        <mandat type="pirat">Dr. Siegfried Hansen</mandat>
        <mandat type="transfer" from="SPD">Ilona Adamski</mandat>
        <mandat type="transfer" from="SPD">Susann Laatz</mandat>
        <fraktion type="piraten" url="http://fraktion.piratenpartei-iz.de/" />
        <story source="http://www.shz.de/nachrichten/lokales/norddeutsche-rundschau/artikeldetails/artikel/spd-frauen-laufen-zu-den-piraten-ueber.html">Dr. Siegfried Hansen war als einziger Pirat in den Kreistag gewählt worden. Kurz vor der konstituierenden Sitzung gaben mit Ilona Adamski und Susann Laatz zwei der insgesamt dreizehn Abgeordneten der SPD ihren Übertritt zu den Piraten und die Gründung einer PIRATEN-Fraktion bekannt. Ilona Adamski übernahm den Vorsitz dieser Fraktion.</story>
      </parlament>
      <gebiet type="Stadt" name="Glückstadt" gs="01061029" localpirates="http://landesportal.piratenpartei-sh.de/glueckstadt/">
        <parlament name="Stadtvertretung" seats="23" ris="http://glueckstadt.de/Verwaltung-Politik/Politik/Stadtvertretung">
          <mandat type="pirat" multi="2">Dr. Siegfried Hansen</mandat>
          <mandat type="pirat">Sebastian Kolpert</mandat>
          <fraktion type="piraten" url="http://landesportal.piratenpartei-sh.de/fraktion-glueckstadt/" />
        </parlament>
      </gebiet>
    </gebiet>
    <gebiet type="Landkreis" name="Kreis Nordfriesland" gs="01054000" localpirates="http://landesportal.piratenpartei-sh.de/nordfriesland/">
      <parlament name="Kreistag" seats="52" ris="http://ratsinfo.nordfriesland.de/sdnet/gremien/?__=LfyIfvCWq8SpBQj0MiyHawGWr8Tq8Sj1SmzHcxEXr8Sm4Pi2KfyJhwDWsBSqGJ">
        <mandat type="pirat">Timo Ploog</mandat>
        <fraktion type="fremd" name="Bündnis 90/Die Grünen" url="http://www.gruene-nf.de/kreistagsfraktion-nf/" />
      </parlament>
      <gebiet type="Gemeinde" name="Sylt" gs="01054168" localpirates="http://landesportal.piratenpartei-sh.de/sylt/">
        <parlament name="Gemeindevertretung" seats="36" ris="https://westerland.more-rubin1.de/gremien_pers.php?submenu=3&amp;Kuerzel=GVSYLT&amp;entrygremien=0&amp;sortgremien=Bezeichnung">
          <mandat type="pirat">Christian Thiessen</mandat>
          <fraktion type="none" />
        </parlament>
      </gebiet>
    </gebiet>
    <gebiet type="Landkreis" name="Kreis Segeberg" gs="01060000" localpirates="http://landesportal.piratenpartei-sh.de/kreis-segeberg/">
      <parlament name="Kreistag" seats="56" ris="https://kreis-se.info/bi/pa021.asp">
        <mandat type="pirat">Thomas Wilken</mandat>
        <mandat type="pirat">Toni Köppen</mandat>
        <fraktion type="piraten" url="http://landesportal.piratenpartei-sh.de/fraktion-segeberg/" />
      </parlament>
    </gebiet>
    <gebiet type="Landkreis" name="Kreis Rendsburg-Eckernförde" gs="01058000" localpirates="http://landesportal.piratenpartei-sh.de/rendsburg-eckernfoerde/">
      <parlament name="Kreistag" seats="49" ris="http://www.kreis-rendsburg-eckernfoerde.de/politik/gremien_risoinfo_index__3_31_1_mitgliedergremium_detail.html">
        <mandat type="pirat">Hans-Werner Last</mandat>
        <fraktion type="none" />
      </parlament>
    </gebiet>
    <gebiet type="Landkreis" name="Kreis Pinneberg" gs="01056000" localpirates="http://landesportal.piratenpartei-sh.de/pinneberg/">
      <parlament name="Kreistag" seats="44" ris="http://www.kreis-pinneberg.de/Politik/Kreistagsinformationssystem/Kreistag.html">
        <mandat type="pirat">Sven Lange</mandat>
        <fraktion type="gemeinsam" name="DIE LINKE &amp; PIRATEN">
          <partner partei="LINKE" num="1" />
        </fraktion>
      </parlament>
    </gebiet>
    <gebiet type="Landkreis" name="Kreis Dithmarschen" gs="01051000" localpirates="http://landesportal.piratenpartei-sh.de/dithmarschen/">
      <parlament name="Kreistag" seats="48" ris="http://www.dithmarschen.de/index.phtml?mNavID=164.800&amp;sNavID=647.48&amp;La=1">
        <mandat type="pirat">Axel Sieck</mandat>
        <fraktion type="none" />
      </parlament>
    </gebiet>
  </bundesland>

  <bundesland name="Hamburg" gs="02000000" localpirates="http://www.piratenpartei-hamburg.de/">
    <gebiet type="Bezirk" name="Hamburg-Mitte" localkey="1">
      <parlament name="Bezirksversammlung" seats="51" ris="http://ratsinformation.web.hamburg.de:84/bi/pa021.asp">
        <mandat type="pirat">Andreas Gerhold</mandat>
        <mandat type="pirat">Michael Büker</mandat>
        <mandat type="transfer" from="GRÜNE">Gül Aydın</mandat>
        <fraktion type="piraten" url="http://hamburg-mitte.bezirkspiraten.de/" />
        <story source="http://hamburg-mitte.bezirkspiraten.de/2012/06/verstarkung-fur-die-piratenpartei-in-der-bezirksversammlung-hamburg-mitte-piraten-grunden-fraktion/">Nach der Wahl zur Bezirksversammlung am 20. Februar 2011 arbeiteten Andreas Gerhold und Michael Büker zunächst als PIRATEN-Gruppe ohne Fraktionsstatus. Im Juni 2012 trat Gül Aydın von den Grünen über und ermöglichte so die Gründung der PIRATEN-Fraktion.</story>
      </parlament>
    </gebiet>
    <gebiet type="Bezirk" name="Bergedorf" localkey="6" localpirates="http://bergedorf.piraten-hh.de/">
      <parlament name="Bezirksversammlung" seats="49" ris="http://ratsinformation.web.hamburg.de:81/bi/pa021.asp">
        <mandat type="pirat">Jan Penz</mandat>
        <fraktion type="none" />
      </parlament>
    </gebiet>
  </bundesland>

  <bundesland name="Niedersachsen" gs="03000000" localpirates="http://piratenpartei-niedersachsen.de/">
    <gebiet type="Kommunalverband besonderer Art" name="Region Hannover" gs="03241000" localpirates="http://www.piratenhannover.de/">
      <parlament name="Regionsversammlung" seats="85" ris="http://www.hannover.de/Leben-in-der-Region-Hannover/Politik/Politische-Gremien/Die-Region-Hannover-politisch/Regionsversammlung">
        <mandat type="pirat">Hans-Jürgen Hey</mandat>
        <fraktion type="gemeinsam" name="Linke &amp; Piraten">
          <partner partei="LINKE" num="1" />
        </fraktion>
        <story source="http://www.piratenhannover.de/3659/neue-gruppe-in-der-regionsversammlung-fleischmann-die-linke-und-hey-piraten/">Ralf Kleyer und Hans-Jürgen Hey waren im September 2011 auf der PIRATEN-Liste in die Regionsversammlung gewählt worden und hatten eine PIRATEN-Fraktion gebildet. Im September 2013 trat aber Ralf Kleyer aus der Piratenpartei aus. Mit Auflösung der PIRATEN-Fraktion schloss sich Hans-Jürgen Hey mit einem Abgeordneten der Linken zu einer Gruppe zusammen.</story>
      </parlament>
      <gebiet type="Stadt" name="Hannover" gs="03241001">
        <parlament name="Stadtrat" seats="64" ris="https://e-government.hannover-stadt.de/lhhsimwebre.nsf">
          <mandat type="pirat">Dr. Jür­gen Jung­hä­nel</mandat>
          <mandat type="pirat">Dirk Hillbrecht</mandat>
          <fraktion type="piraten" url="http://piraten-rat-hannover.de/"/>
        </parlament>
        <gebiet type="Stadtbezirk" name="Vahrenwald-List" localkey="2">
          <parlament name="Stadtbezirksrat" seats="21" ris="http://www.hannover.de/Leben-in-der-Region-Hannover/Politik/Politische-Gremien/Landeshaupstadt-Hannover/Bezirksr%C3%A4te/Stadtbezirk-2-Vahrenwald-List">
            <mandat type="pirat">Reiner Budnick</mandat>
            <fraktion type="none" />
          </parlament>
        </gebiet>
        <gebiet type="Stadtbezirk" name="Misburg-Anderten" localkey="5">
          <parlament name="Stadtbezirksrat" seats="19" ris="http://www.hannover.de/Leben-in-der-Region-Hannover/Politik/Politische-Gremien/Landeshaupstadt-Hannover/Bezirksr%C3%A4te/Stadtbezirk-5-Misburg-Anderten">
            <mandat type="pirat">Hannes Amelung</mandat>
            <fraktion type="none" />
          </parlament>
        </gebiet>
        <gebiet type="Stadtbezirk" name="Südstadt-Bult" localkey="7">
          <parlament name="Stadtbezirksrat" seats="21" ris="http://www.hannover.de/Leben-in-der-Region-Hannover/Politik/Politische-Gremien/Landeshaupstadt-Hannover/Bezirksr%C3%A4te/Stadtbezirk-7-S%C3%BCdstadt-Bult">
            <mandat type="pirat">Miriam Hadj Hassine</mandat>
            <fraktion type="none" />
          </parlament>
        </gebiet>
